# Generated by Django 3.0.7 on 2020-06-17 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('kilometri', models.IntegerField()),
                ('potrosnja', models.IntegerField()),
                ('vrsta', models.CharField(max_length=100)),
                ('godina', models.IntegerField()),
                ('snaga', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image_main', models.ImageField(upload_to='images')),
                ('image1', models.ImageField(blank=True, upload_to='images')),
                ('image2', models.ImageField(blank=True, upload_to='images')),
                ('image3', models.ImageField(blank=True, upload_to='images')),
                ('is_published', models.BooleanField(default=True)),
                ('categories', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='listings.Category')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dealers.Dealer')),
            ],
        ),
    ]
