# Generated by Django 3.0.7 on 2020-06-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200618_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='godina',
        ),
        migrations.AddField(
            model_name='listing',
            name='year',
            field=models.IntegerField(choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, verbose_name='year'),
        ),
    ]
