# Generated by Django 4.1 on 2022-08-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_auto_20200703_0748"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.IntegerField(
                choices=[
                    (2005, 2005),
                    (2006, 2006),
                    (2007, 2007),
                    (2008, 2008),
                    (2009, 2009),
                    (2010, 2010),
                    (2011, 2011),
                    (2012, 2012),
                    (2013, 2013),
                    (2014, 2014),
                    (2015, 2015),
                    (2016, 2016),
                    (2017, 2017),
                    (2018, 2018),
                    (2019, 2019),
                    (2020, 2020),
                    (2021, 2021),
                    (2022, 2022),
                ],
                default=2022,
                verbose_name="year",
            ),
        ),
    ]
