# Generated by Django 4.1 on 2022-09-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrape", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selectcar",
            name="brand",
            field=models.CharField(
                choices=[("BMW", "BMW"), ("MR", "Mercedes"), ("HN", "Honda")],
                default="BMW",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="selectcar",
            name="car_model",
            field=models.CharField(
                choices=[("X1", "X1"), ("X2", "X2"), ("X3", "X3"), ("AM", "Amaze")],
                default="X1",
                max_length=30,
            ),
        ),
    ]
