# Generated by Django 4.1 on 2022-09-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrape", "0002_alter_selectcar_brand_alter_selectcar_car_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selectcar",
            name="car_model",
            field=models.CharField(
                choices=[
                    ("X1", "X1"),
                    ("X2", "X2"),
                    ("X3", "X3"),
                    ("AM", "Amaze"),
                    ("EC", "E-class"),
                ],
                default="X1",
                max_length=30,
            ),
        ),
    ]
